// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://juigucueyykqcnljiyvn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1aWd1Y3VleXlrcWNubGppeXZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1OTYwOTcsImV4cCI6MjA2OTE3MjA5N30.2v3sLMa4cEWBgCGf7GcZ1RS5JpDyww5DM9RNlKrspjE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});